/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IConvexTokenFactory,
  IConvexTokenFactoryInterface,
} from "../IConvexTokenFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        internalType: "uint8",
        name: "decimals",
        type: "uint8",
      },
    ],
    name: "deployPoolToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IConvexTokenFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IConvexTokenFactoryInterface {
    return new utils.Interface(_abi) as IConvexTokenFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConvexTokenFactory {
    return new Contract(address, _abi, signerOrProvider) as IConvexTokenFactory;
  }
}
