/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IVestedEscrow, IVestedEscrowInterface } from "../IVestedEscrow";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_recipient",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "_amount",
        type: "uint256[]",
      },
    ],
    name: "fund",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IVestedEscrow__factory {
  static readonly abi = _abi;
  static createInterface(): IVestedEscrowInterface {
    return new utils.Interface(_abi) as IVestedEscrowInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVestedEscrow {
    return new Contract(address, _abi, signerOrProvider) as IVestedEscrow;
  }
}
